name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.4.0
        virtualenvs-create: true

    - name: Install dependencies
      run: poetry install
      working-directory: ${{ github.workspace }}

    - name: Run tests
      run: poetry run pytest
      working-directory: ${{ github.workspace }}

    - name: Run linter
      run: poetry run flake8
      working-directory: ${{ github.workspace }}
