name: Python CI

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Set up Poetry
      uses: dmerejkowsky/action-poetry@v2
      with:
        virtualenvs.create: true

    - name: Install dependencies
      run: poetry install
      working-directory: ${{ github.workspace }}/data_miners  # <-- Add this line

    - name: Run tests
      run: poetry run pytest
      working-directory: ${{ github.workspace }}/data_miners  # <-- Add this line

    - name: Run linter
      run: poetry run flake8 --exclude=.git,__pycache__,.venv --max-line-length=120
      working-directory: ${{ github.workspace }}/data_miners  # <-- Add this line
